# Generated by Django 4.0.10 on 2023-07-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('duracion_minutos', models.IntegerField()),
                ('familia', models.CharField(blank=True, max_length=2, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
